#!/opt/homebrew/bin/bash

#TODO: rediriger les entrées et sorties standards vers ce script

readFile(){
    #-r pour ignorer les caractères d'échappement
    while read -r LINE; do
        if [[ ${LINE%% *} == $1 ]]; then
            echo "${LINE#* }"
        fi
    done < "liste-bot.txt"
    echo ""
}


#vérifier si le nombre de paramètres est correct
if [ $# -lt 1 ] || [ $# -gt 2 ]; then #si moins d'un paramètre ou plus que deux
    #>&2 pour rediriger le message vers la sortie standard d'erreur
    echo "chat-bot destinataire [pseudo]" >&2
    exit 1
fi

#s'il n'y a pas de 2e argument, le réceptionniste sera "bot" par défaut
if [ -z "$2" ]; then
    rec="bot"
else
    rec=$2  #receptionniste
fi

dest=$1 #destinataire

coproc MY_PROC { ./chat "$rec" "$dest" --bot; }



while read -r input <&"${MY_PROC[0]}"; do
    entry="${input#* }"


    if [[ "$(echo "$entry" | xargs)" == "liste" ]]; then
        echo "$(ls)" >&"${MY_PROC[1]}"

    elif [[ "$(echo "$entry" | xargs)" == "li FICHIER" ]]; then
        echo "TODO" >&"${MY_PROC[1]}"

    elif [[ "$(echo "$entry" | xargs)" == "qui suis-je" ]]; then
        echo "$dest" >&"${MY_PROC[1]}"

    elif [[ "$(echo "$entry" | xargs)" == "au revoir" ]]; then
        echo "Au revoir $dest." >&"${MY_PROC[1]}"

        exit 0
    else
        ret=$(readFile "$entry")
        if [[ "$ret" == "" ]]; then
            echo "🤖 ?" >&"${MY_PROC[1]}"
        else
            echo "$ret" >&"${MY_PROC[1]}"
        fi
    fi
done